// Export all types
export * from './types/enums';

// Export all interfaces
export * from './interfaces/analisis';
export * from './interfaces/analisis-service';
export * from './interfaces/catalogo';
export * from './interfaces/common';
export * from './interfaces/contacto';
export * from './interfaces/cultivar';
export * from './interfaces/pureza';
export * from './interfaces/germinacion';
export * from './interfaces/pms';
export * from './interfaces/tetrazolio';
export * from './interfaces/dosn';
export * from './interfaces/especie';
export * from './interfaces/lote';
export * from './interfaces/lote-simple';
export * from './interfaces/malezas';
export * from './interfaces/repeticiones';
export * from './interfaces/usuario';
export * from './interfaces/valores-germ';